version: '3.9'
services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/django/static
    ports:
      - 80:80
    depends_on:
      - app
  app:
    build: .
    volumes:
      - .:/django
      - static_volume:/django/static
    image: app:django
    container_name: django_container
    env_file:
      - ./.env
    command: gunicorn SNS.wsgi:application --bind 0.0.0.0:8000

volumes:
  static_volume: